#!/usr/bin/env python3
"""Generate catalogue entries to demonstrate scaling."""

import os
import textwrap

CATALOGUE_DIR = os.path.join(os.path.dirname(__file__), "..", "content", "catalogue")

ENTRIES = {
    "tools": [
        {
            "title": "Notion",
            "tagline": "All-in-one workspace for notes, docs, wikis, and project management with real-time collaboration.",
            "domains": ["software-engineering", "education", "business", "publishing"],
            "collaboration-types": ["distributed", "co-creation"],
            "scales": ["small-team", "organization"],
            "modalities": ["remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Figma",
            "tagline": "Browser-based design tool enabling real-time collaboration on UI/UX prototypes and design systems.",
            "domains": ["design", "software-engineering", "education"],
            "collaboration-types": ["co-design", "distributed"],
            "scales": ["pair", "small-team", "organization"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Obsidian",
            "tagline": "Knowledge management tool using linked markdown files for personal and collaborative note-taking.",
            "domains": ["education", "social-sciences", "publishing"],
            "collaboration-types": ["co-creation", "open-source"],
            "scales": ["pair", "small-team"],
            "modalities": ["remote", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Overleaf",
            "tagline": "Collaborative LaTeX editor for academic writing with real-time co-authoring and version history.",
            "domains": ["education", "social-sciences", "publishing"],
            "collaboration-types": ["co-creation", "distributed", "interdisciplinary"],
            "scales": ["pair", "small-team"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Trello",
            "tagline": "Visual project management tool using boards, lists, and cards for task tracking and team coordination.",
            "domains": ["business", "software-engineering", "education"],
            "collaboration-types": ["distributed", "co-production"],
            "scales": ["small-team", "organization"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Airtable",
            "tagline": "Flexible spreadsheet-database hybrid for organizing research data and collaborative project tracking.",
            "domains": ["business", "social-sciences", "citizen-science"],
            "collaboration-types": ["distributed", "co-production"],
            "scales": ["small-team", "organization"],
            "modalities": ["remote"],
            "maturity": "established",
        },
        {
            "title": "Canva",
            "tagline": "Graphic design platform enabling teams to create visual content collaboratively with shared brand kits.",
            "domains": ["arts-culture", "education", "business", "publishing"],
            "collaboration-types": ["co-creation", "distributed"],
            "scales": ["small-team", "organization"],
            "modalities": ["remote"],
            "maturity": "established",
        },
        {
            "title": "Jamboard",
            "tagline": "Google's collaborative digital whiteboard for brainstorming and visual ideation sessions.",
            "domains": ["education", "design", "business"],
            "collaboration-types": ["co-design", "co-creation"],
            "scales": ["pair", "small-team"],
            "modalities": ["remote", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "GitLab",
            "tagline": "DevOps platform with integrated CI/CD, issue tracking, and code review for collaborative software development.",
            "domains": ["software-engineering", "citizen-science"],
            "collaboration-types": ["open-source", "distributed", "co-production"],
            "scales": ["small-team", "organization", "community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Mentimeter",
            "tagline": "Interactive presentation tool with live polls, quizzes, and word clouds for audience engagement.",
            "domains": ["education", "business", "public-policy"],
            "collaboration-types": ["participatory", "crowdsourcing"],
            "scales": ["small-team", "organization", "community"],
            "modalities": ["in-person", "remote", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Gather Town",
            "tagline": "Virtual space platform combining video chat with spatial proximity for informal collaboration.",
            "domains": ["education", "software-engineering", "arts-culture"],
            "collaboration-types": ["distributed", "community-based"],
            "scales": ["small-team", "organization"],
            "modalities": ["remote"],
            "maturity": "emerging",
        },
        {
            "title": "Zulip",
            "tagline": "Topic-based team chat platform designed for organized, asynchronous communication in distributed teams.",
            "domains": ["software-engineering", "education", "citizen-science"],
            "collaboration-types": ["open-source", "distributed"],
            "scales": ["small-team", "organization", "community"],
            "modalities": ["remote"],
            "maturity": "established",
        },
        {
            "title": "QGIS",
            "tagline": "Open-source geographic information system for collaborative spatial data analysis and mapping.",
            "domains": ["environmental-science", "urban-planning", "citizen-science", "agriculture"],
            "collaboration-types": ["open-source", "interdisciplinary", "community-based"],
            "scales": ["small-team", "community"],
            "modalities": ["remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "REDCap",
            "tagline": "Secure web application for building and managing online surveys and databases in research studies.",
            "domains": ["healthcare", "social-sciences", "education"],
            "collaboration-types": ["interdisciplinary", "distributed"],
            "scales": ["small-team", "organization", "multi-org"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Open Science Framework",
            "tagline": "Free platform for managing research projects with preregistration, data sharing, and collaboration tools.",
            "domains": ["social-sciences", "education", "healthcare", "environmental-science"],
            "collaboration-types": ["open-source", "distributed", "interdisciplinary"],
            "scales": ["pair", "small-team", "multi-org"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
    ],
    "methods": [
        {
            "title": "Delphi Method",
            "tagline": "Structured communication technique using iterative rounds of expert consultation to build consensus.",
            "domains": ["healthcare", "public-policy", "education", "business"],
            "collaboration-types": ["interdisciplinary", "distributed"],
            "scales": ["small-team", "organization"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Focus Groups",
            "tagline": "Facilitated group discussions to gather qualitative insights on attitudes, perceptions, and experiences.",
            "domains": ["social-sciences", "healthcare", "business", "design"],
            "collaboration-types": ["participatory", "co-design"],
            "scales": ["small-team"],
            "modalities": ["in-person", "remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Design Thinking",
            "tagline": "Human-centered iterative approach to problem-solving through empathy, ideation, prototyping, and testing.",
            "domains": ["design", "business", "education", "healthcare"],
            "collaboration-types": ["co-design", "co-creation", "interdisciplinary"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Citizen Assembly",
            "tagline": "Deliberative democratic method where randomly selected citizens discuss and make policy recommendations.",
            "domains": ["public-policy", "urban-planning", "environmental-science"],
            "collaboration-types": ["participatory", "community-based", "transdisciplinary"],
            "scales": ["organization", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Photovoice",
            "tagline": "Participatory research method where community members use photography to document and discuss social issues.",
            "domains": ["social-sciences", "healthcare", "urban-planning", "arts-culture"],
            "collaboration-types": ["participatory", "community-based", "co-production"],
            "scales": ["small-team", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Living Lab",
            "tagline": "Open innovation ecosystem operating in real-world settings where users co-create solutions with researchers.",
            "domains": ["urban-planning", "design", "software-engineering", "healthcare"],
            "collaboration-types": ["co-creation", "co-design", "transdisciplinary"],
            "scales": ["organization", "multi-org", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Hackathon",
            "tagline": "Time-bounded collaborative event where diverse teams rapidly prototype solutions to defined challenges.",
            "domains": ["software-engineering", "design", "citizen-science", "healthcare"],
            "collaboration-types": ["co-creation", "interdisciplinary", "crowdsourcing"],
            "scales": ["small-team", "organization", "community"],
            "modalities": ["in-person", "remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Nominal Group Technique",
            "tagline": "Structured decision-making method combining individual idea generation with group ranking and discussion.",
            "domains": ["healthcare", "business", "education"],
            "collaboration-types": ["participatory", "interdisciplinary"],
            "scales": ["small-team"],
            "modalities": ["in-person", "remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Future Search",
            "tagline": "Large-group planning method bringing stakeholders together to create shared vision and action plans.",
            "domains": ["public-policy", "urban-planning", "business", "education"],
            "collaboration-types": ["participatory", "co-design", "transdisciplinary"],
            "scales": ["organization", "multi-org"],
            "modalities": ["in-person"],
            "maturity": "established",
        },
        {
            "title": "Appreciative Inquiry",
            "tagline": "Strengths-based change methodology that engages stakeholders in discovering and building on organizational assets.",
            "domains": ["business", "education", "healthcare"],
            "collaboration-types": ["participatory", "co-creation"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Open Space Technology",
            "tagline": "Self-organizing conference format where participants create and manage their own agenda around a theme.",
            "domains": ["business", "education", "public-policy"],
            "collaboration-types": ["participatory", "community-based"],
            "scales": ["organization", "community"],
            "modalities": ["in-person"],
            "maturity": "well-documented",
        },
        {
            "title": "Most Significant Change",
            "tagline": "Participatory monitoring and evaluation method using storytelling to capture and analyze program impact.",
            "domains": ["social-sciences", "healthcare", "education", "public-policy"],
            "collaboration-types": ["participatory", "community-based", "co-production"],
            "scales": ["organization", "multi-org"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
    ],
    "frameworks": [
        {
            "title": "Triple Helix Model",
            "tagline": "Framework describing university-industry-government interactions driving innovation and economic development.",
            "domains": ["business", "public-policy", "education"],
            "collaboration-types": ["interdisciplinary", "transdisciplinary", "co-production"],
            "scales": ["multi-org", "community"],
            "modalities": ["hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Community-Based Participatory Research",
            "tagline": "Collaborative framework that equitably involves community members and researchers in all phases of research.",
            "domains": ["healthcare", "social-sciences", "public-policy", "education"],
            "collaboration-types": ["participatory", "community-based", "co-production"],
            "scales": ["small-team", "organization", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Mode 2 Knowledge Production",
            "tagline": "Framework describing transdisciplinary, application-driven knowledge creation outside traditional academic boundaries.",
            "domains": ["social-sciences", "education", "public-policy"],
            "collaboration-types": ["transdisciplinary", "interdisciplinary", "co-production"],
            "scales": ["organization", "multi-org"],
            "modalities": ["hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Cynefin Framework",
            "tagline": "Sense-making framework that helps teams choose appropriate collaboration strategies based on problem complexity.",
            "domains": ["business", "public-policy", "disaster-response"],
            "collaboration-types": ["co-design", "distributed"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Responsible Research and Innovation",
            "tagline": "EU framework for inclusive and sustainable research through anticipation, reflexivity, inclusion, and responsiveness.",
            "domains": ["public-policy", "environmental-science", "healthcare", "social-sciences"],
            "collaboration-types": ["participatory", "transdisciplinary", "co-design"],
            "scales": ["multi-org", "community"],
            "modalities": ["hybrid"],
            "maturity": "established",
        },
        {
            "title": "Collective Impact Framework",
            "tagline": "Structured approach for cross-sector collaboration to address complex social problems through shared agenda.",
            "domains": ["public-policy", "healthcare", "education", "urban-planning"],
            "collaboration-types": ["co-production", "community-based", "transdisciplinary"],
            "scales": ["multi-org", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Theory of Change",
            "tagline": "Planning and evaluation framework mapping how activities lead to desired outcomes through causal pathways.",
            "domains": ["public-policy", "social-sciences", "education", "healthcare"],
            "collaboration-types": ["participatory", "co-design"],
            "scales": ["small-team", "organization", "multi-org"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Quadruple Helix Innovation",
            "tagline": "Extension of Triple Helix adding civil society as fourth actor in innovation ecosystems.",
            "domains": ["public-policy", "business", "education", "urban-planning"],
            "collaboration-types": ["transdisciplinary", "co-creation", "community-based"],
            "scales": ["multi-org", "community"],
            "modalities": ["hybrid"],
            "maturity": "emerging",
        },
        {
            "title": "Boundary Object Theory",
            "tagline": "Framework explaining how shared artifacts enable coordination across diverse communities of practice.",
            "domains": ["social-sciences", "design", "software-engineering"],
            "collaboration-types": ["interdisciplinary", "co-production"],
            "scales": ["small-team", "organization", "multi-org"],
            "modalities": ["in-person", "remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Participatory Action Research Framework",
            "tagline": "Systematic framework for community members to investigate and take action on issues affecting their lives.",
            "domains": ["social-sciences", "education", "healthcare", "agriculture"],
            "collaboration-types": ["participatory", "community-based", "co-production"],
            "scales": ["small-team", "organization", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Agile Methodology",
            "tagline": "Iterative development framework emphasizing adaptive planning, cross-functional teams, and continuous delivery.",
            "domains": ["software-engineering", "business", "design"],
            "collaboration-types": ["co-production", "distributed", "co-design"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person", "remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Social-Ecological Systems Framework",
            "tagline": "Analytical framework for understanding interactions between social and ecological systems in governance contexts.",
            "domains": ["environmental-science", "agriculture", "public-policy"],
            "collaboration-types": ["interdisciplinary", "transdisciplinary", "community-based"],
            "scales": ["multi-org", "community"],
            "modalities": ["hybrid"],
            "maturity": "well-documented",
        },
    ],
    "case-studies": [
        {
            "title": "Wikipedia",
            "tagline": "The world's largest collaboratively edited encyclopedia maintained by a global volunteer community.",
            "domains": ["education", "publishing", "citizen-science"],
            "collaboration-types": ["crowdsourcing", "open-source", "community-based"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Human Genome Project",
            "tagline": "International 13-year research effort to map the complete human genome through multi-institutional collaboration.",
            "domains": ["healthcare", "social-sciences"],
            "collaboration-types": ["interdisciplinary", "distributed", "co-production"],
            "scales": ["multi-org", "community"],
            "modalities": ["hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "OpenStreetMap",
            "tagline": "Collaborative project to create a free editable geographic database of the world through volunteer mapping.",
            "domains": ["urban-planning", "citizen-science", "disaster-response"],
            "collaboration-types": ["crowdsourcing", "open-source", "community-based"],
            "scales": ["community"],
            "modalities": ["remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Linux Kernel Development",
            "tagline": "Distributed open-source collaboration involving thousands of developers maintaining the world's most used OS kernel.",
            "domains": ["software-engineering"],
            "collaboration-types": ["open-source", "distributed", "community-based"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Barcelona Superblock Program",
            "tagline": "Participatory urban redesign transforming city blocks to prioritize pedestrians and community space.",
            "domains": ["urban-planning", "public-policy", "environmental-science"],
            "collaboration-types": ["participatory", "co-design", "community-based"],
            "scales": ["organization", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Galaxy Zoo",
            "tagline": "Citizen science project where volunteers classify galaxies from telescope images to advance astronomy research.",
            "domains": ["citizen-science", "education"],
            "collaboration-types": ["crowdsourcing", "distributed", "community-based"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Fab Lab Network",
            "tagline": "Global network of community fabrication laboratories enabling local digital manufacturing and collaborative innovation.",
            "domains": ["design", "manufacturing", "education"],
            "collaboration-types": ["open-source", "community-based", "co-creation"],
            "scales": ["small-team", "community"],
            "modalities": ["in-person"],
            "maturity": "established",
        },
        {
            "title": "NHS Integrated Care Systems",
            "tagline": "UK health system partnerships bringing together providers and commissioners to plan services collaboratively.",
            "domains": ["healthcare", "public-policy"],
            "collaboration-types": ["co-production", "interdisciplinary", "transdisciplinary"],
            "scales": ["multi-org", "community"],
            "modalities": ["hybrid"],
            "maturity": "established",
        },
        {
            "title": "Mozilla Firefox Development",
            "tagline": "Open-source browser development combining paid engineers and global volunteer contributors.",
            "domains": ["software-engineering"],
            "collaboration-types": ["open-source", "distributed", "community-based"],
            "scales": ["organization", "community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Transition Towns Movement",
            "tagline": "Grassroots community organizing for local resilience and sustainability in response to climate change.",
            "domains": ["environmental-science", "urban-planning", "agriculture"],
            "collaboration-types": ["community-based", "participatory", "co-creation"],
            "scales": ["community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Medellín Urban Innovation",
            "tagline": "Participatory transformation of a violence-affected city through inclusive infrastructure and social programs.",
            "domains": ["urban-planning", "public-policy", "education"],
            "collaboration-types": ["participatory", "co-design", "transdisciplinary"],
            "scales": ["multi-org", "community"],
            "modalities": ["in-person"],
            "maturity": "well-documented",
        },
        {
            "title": "eBird Global Birding Database",
            "tagline": "Citizen science platform collecting worldwide bird observations to drive avian research and conservation.",
            "domains": ["environmental-science", "citizen-science", "education"],
            "collaboration-types": ["crowdsourcing", "community-based", "distributed"],
            "scales": ["community"],
            "modalities": ["remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Mondragon Cooperative",
            "tagline": "Worker-owned cooperative federation in Spain demonstrating collaborative governance in business at scale.",
            "domains": ["business", "manufacturing", "education"],
            "collaboration-types": ["co-production", "community-based", "participatory"],
            "scales": ["organization", "multi-org"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Arduino Open Hardware",
            "tagline": "Open-source electronics platform built by a global community of makers, educators, and engineers.",
            "domains": ["design", "education", "manufacturing", "software-engineering"],
            "collaboration-types": ["open-source", "co-creation", "community-based"],
            "scales": ["community"],
            "modalities": ["remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Auroville Experimental Township",
            "tagline": "International community in India experimenting with collective governance and sustainable living.",
            "domains": ["urban-planning", "education", "arts-culture", "agriculture"],
            "collaboration-types": ["community-based", "co-creation", "transdisciplinary"],
            "scales": ["community"],
            "modalities": ["in-person"],
            "maturity": "established",
        },
    ],
    "datasets": [
        {
            "title": "ORCID Public Data File",
            "tagline": "Annual data dump of researcher identifiers and affiliations enabling analysis of scientific collaboration networks.",
            "domains": ["social-sciences", "education", "publishing"],
            "collaboration-types": ["open-source", "distributed"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
            "platform": "orcid",
        },
        {
            "title": "Crossref Metadata API",
            "tagline": "Scholarly metadata for over 130 million research outputs enabling citation and co-authorship analysis.",
            "domains": ["social-sciences", "education", "publishing"],
            "collaboration-types": ["open-source", "distributed"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
            "platform": "crossref",
        },
        {
            "title": "WHO Global Health Observatory",
            "tagline": "Comprehensive health statistics and indicators from 194 countries for collaborative health research.",
            "domains": ["healthcare", "public-policy", "social-sciences"],
            "collaboration-types": ["interdisciplinary", "distributed"],
            "scales": ["multi-org", "community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
            "platform": "who",
        },
        {
            "title": "OpenAlex Research Graph",
            "tagline": "Open catalog of scholarly works, authors, institutions, and concepts replacing Microsoft Academic Graph.",
            "domains": ["social-sciences", "education", "publishing"],
            "collaboration-types": ["open-source", "distributed", "interdisciplinary"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "established",
            "platform": "openalex",
        },
        {
            "title": "Global Biodiversity Information Facility",
            "tagline": "International open data infrastructure providing access to over 2 billion species occurrence records.",
            "domains": ["environmental-science", "citizen-science", "agriculture"],
            "collaboration-types": ["open-source", "distributed", "community-based"],
            "scales": ["multi-org", "community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
            "platform": "gbif",
        },
        {
            "title": "European Social Survey",
            "tagline": "Cross-national survey measuring attitudes, beliefs, and behaviour across 30+ European countries biennially.",
            "domains": ["social-sciences", "public-policy", "education"],
            "collaboration-types": ["interdisciplinary", "distributed", "co-production"],
            "scales": ["multi-org"],
            "modalities": ["hybrid"],
            "maturity": "well-documented",
            "platform": "ess",
        },
        {
            "title": "GitHub Archive",
            "tagline": "Time-stamped archive of public GitHub events enabling analysis of open-source collaboration patterns.",
            "domains": ["software-engineering", "social-sciences"],
            "collaboration-types": ["open-source", "distributed"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
            "platform": "github",
        },
        {
            "title": "Humanitarian Data Exchange",
            "tagline": "Open platform for sharing humanitarian data across organizations responding to crises worldwide.",
            "domains": ["disaster-response", "public-policy", "healthcare"],
            "collaboration-types": ["distributed", "open-source", "community-based"],
            "scales": ["multi-org", "community"],
            "modalities": ["remote"],
            "maturity": "established",
            "platform": "humdata",
        },
        {
            "title": "Urban Observatory Dataset",
            "tagline": "Comparative data from cities worldwide enabling analysis of urban development and governance patterns.",
            "domains": ["urban-planning", "public-policy", "environmental-science"],
            "collaboration-types": ["interdisciplinary", "distributed"],
            "scales": ["multi-org"],
            "modalities": ["remote"],
            "maturity": "emerging",
            "platform": "urban-observatory",
        },
        {
            "title": "OpenNeuro Brain Imaging",
            "tagline": "Free platform for sharing neuroimaging data to accelerate collaborative brain research.",
            "domains": ["healthcare", "social-sciences"],
            "collaboration-types": ["open-source", "interdisciplinary", "distributed"],
            "scales": ["multi-org", "community"],
            "modalities": ["remote"],
            "maturity": "established",
            "platform": "openneuro",
        },
        {
            "title": "Wikipedia Edit History",
            "tagline": "Complete revision history of all Wikipedia articles enabling analysis of collaborative knowledge production.",
            "domains": ["social-sciences", "education", "publishing"],
            "collaboration-types": ["crowdsourcing", "open-source", "community-based"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
            "platform": "wikimedia",
        },
        {
            "title": "Stack Overflow Data Dump",
            "tagline": "Anonymized dump of all questions, answers, and user interactions from the developer Q&A platform.",
            "domains": ["software-engineering", "education"],
            "collaboration-types": ["crowdsourcing", "community-based", "distributed"],
            "scales": ["community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
            "platform": "stack-exchange",
        },
    ],
    "resources": [
        {
            "title": "The Handbook of Action Research",
            "tagline": "Comprehensive reference covering participatory inquiry theory, practice, and applications across disciplines.",
            "domains": ["social-sciences", "education", "healthcare"],
            "collaboration-types": ["participatory", "co-production", "community-based"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Liberating Structures Toolkit",
            "tagline": "Collection of 33 facilitation microstructures for engaging everyone in shaping group decisions.",
            "domains": ["business", "education", "healthcare", "public-policy"],
            "collaboration-types": ["participatory", "co-creation"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "IAP2 Public Participation Spectrum",
            "tagline": "Framework describing increasing levels of public impact from informing to empowering in decision-making.",
            "domains": ["public-policy", "urban-planning", "environmental-science"],
            "collaboration-types": ["participatory", "community-based"],
            "scales": ["organization", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Open Source Guide",
            "tagline": "GitHub's comprehensive guide to launching and sustaining open-source projects with community best practices.",
            "domains": ["software-engineering", "education"],
            "collaboration-types": ["open-source", "community-based", "distributed"],
            "scales": ["small-team", "community"],
            "modalities": ["remote"],
            "maturity": "well-documented",
        },
        {
            "title": "Facilitator's Guide to Participatory Decision-Making",
            "tagline": "Practical manual for leading inclusive group processes using the diamond of participatory decision-making.",
            "domains": ["business", "education", "public-policy"],
            "collaboration-types": ["participatory", "co-design"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person"],
            "maturity": "well-documented",
        },
        {
            "title": "FOSTER Open Science Toolkit",
            "tagline": "Training resources and best practices for implementing open science principles in research institutions.",
            "domains": ["education", "social-sciences", "publishing"],
            "collaboration-types": ["open-source", "interdisciplinary", "distributed"],
            "scales": ["organization", "multi-org"],
            "modalities": ["remote", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "Design Justice Network Principles",
            "tagline": "Community-generated principles centering marginalized communities in collaborative design processes.",
            "domains": ["design", "social-sciences", "urban-planning", "arts-culture"],
            "collaboration-types": ["participatory", "co-design", "community-based"],
            "scales": ["small-team", "community"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "The Art of Gathering",
            "tagline": "Guide to designing purposeful collaborative gatherings that transform how groups come together.",
            "domains": ["business", "education", "arts-culture"],
            "collaboration-types": ["participatory", "co-creation"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person"],
            "maturity": "established",
        },
        {
            "title": "Citizen Science Toolkit",
            "tagline": "Step-by-step resources for designing and managing citizen science projects with community volunteers.",
            "domains": ["citizen-science", "environmental-science", "education"],
            "collaboration-types": ["crowdsourcing", "community-based", "participatory"],
            "scales": ["organization", "community"],
            "modalities": ["in-person", "remote", "hybrid"],
            "maturity": "well-documented",
        },
        {
            "title": "Cooperative Development Manual",
            "tagline": "Practical guide for establishing and governing worker cooperatives with democratic decision-making.",
            "domains": ["business", "agriculture", "manufacturing"],
            "collaboration-types": ["co-production", "community-based", "participatory"],
            "scales": ["small-team", "organization"],
            "modalities": ["in-person", "hybrid"],
            "maturity": "established",
        },
        {
            "title": "InnerSource Patterns",
            "tagline": "Documented patterns for applying open-source collaboration practices within organizational boundaries.",
            "domains": ["software-engineering", "business"],
            "collaboration-types": ["open-source", "distributed", "co-production"],
            "scales": ["organization", "multi-org"],
            "modalities": ["remote"],
            "maturity": "emerging",
        },
        {
            "title": "Mapping Collaborative Ecosystems Guide",
            "tagline": "Methodological guide for visualizing and analyzing networks of collaborative actors and relationships.",
            "domains": ["social-sciences", "business", "public-policy"],
            "collaboration-types": ["interdisciplinary", "transdisciplinary"],
            "scales": ["multi-org", "community"],
            "modalities": ["hybrid"],
            "maturity": "emerging",
        },
        {
            "title": "Remote Facilitation Playbook",
            "tagline": "Techniques and tools for running effective collaborative workshops and meetings in distributed teams.",
            "domains": ["business", "education", "design"],
            "collaboration-types": ["distributed", "co-creation", "participatory"],
            "scales": ["small-team", "organization"],
            "modalities": ["remote"],
            "maturity": "established",
        },
        {
            "title": "Transdisciplinary Research Primer",
            "tagline": "Introduction to methods and challenges of research that bridges academic and non-academic knowledge systems.",
            "domains": ["education", "social-sciences", "environmental-science"],
            "collaboration-types": ["transdisciplinary", "interdisciplinary", "co-production"],
            "scales": ["small-team", "multi-org"],
            "modalities": ["hybrid"],
            "maturity": "established",
        },
    ],
}


def make_data_id(title):
    return title.lower().replace(" ", "-").replace("(", "").replace(")", "").replace("'", "").replace("/", "-").replace("&", "and")


def yaml_list(items):
    return "[" + ", ".join(f'"{item}"' for item in items) + "]"


def generate_entry(entry_type, entry):
    data_id = entry.get("data_id", make_data_id(entry["title"]))
    lines = [
        "---",
        f'title: "{entry["title"]}"',
        f'tagline: "{entry["tagline"]}"',
        f'data_id: "{data_id}"',
        f'domains: {yaml_list(entry["domains"])}',
        f'collaboration-types: {yaml_list(entry["collaboration-types"])}',
        f'scales: {yaml_list(entry["scales"])}',
        f'modalities: {yaml_list(entry["modalities"])}',
        f'maturity: "{entry["maturity"]}"',
        'status: "published"',
    ]
    if "platform" in entry:
        lines.append(f'platform: "{entry["platform"]}"')
    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def main():
    total = 0
    for entry_type, entries in ENTRIES.items():
        type_dir = os.path.join(CATALOGUE_DIR, entry_type)
        os.makedirs(type_dir, exist_ok=True)
        for entry in entries:
            data_id = entry.get("data_id", make_data_id(entry["title"]))
            filename = f"{data_id}.md"
            filepath = os.path.join(type_dir, filename)
            if os.path.exists(filepath):
                print(f"  SKIP (exists): {entry_type}/{filename}")
                continue
            content = generate_entry(entry_type, entry)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"  CREATE: {entry_type}/{filename}")
            total += 1
    print(f"\nGenerated {total} new entries.")


if __name__ == "__main__":
    main()
